# Generated by Django 4.1.7 on 2023-03-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(default='Enter more about yourself...', max_length=150)),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
