# Generated by Django 4.1.7 on 2023-03-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subject'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
    ]
