# Generated by Django 4.1.7 on 2023-03-25 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_subject_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('reciever', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(max_length=50, unique=True)),
                ('income_type', models.IntegerField(null=True)),
                ('municipality', models.IntegerField(null=True)),
                ('budget_organization', models.IntegerField(null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('amount', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'payment_item',
            },
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.CharField(default='Enter more about this subject...', max_length=150),
        ),
    ]
