# Generated by Django 4.1.7 on 2023-03-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_paymentitem_alter_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collage',
            field=models.CharField(default=None, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='index',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
