# Generated by Django 4.1.7 on 2023-03-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_collage_user_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='index',
            new_name='student_index',
        ),
    ]
