# Generated by Django 4.1.7 on 2023-03-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_user_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentitem',
            name='purpose',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='reciever',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
